version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: gamified-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./database.db
    volumes:
      - ./backend/database.db:/app/database.db

  frontend:
    build:
      context: ./frontend
    container_name: gamified-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
